#name: sci-tools
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7.11
  - pip
  - pip:
      - git+https://gitlab+deploy-token-5:xWC3GAtXe2jKHvZBPnxe@git.itim.vn/bi/scicontrib.git@1.1#egg=scicontrib
      - numpy==1.21.2
      - pandas==1.3.0
      - pandarallel==1.5.3
      - pyvi==0.1.1
      - requests==2.26.0
      - python-dateutil==2.8.1
      - gensim==3.8.1
      - fasttext==0.9.2
      - uvicorn[standard]==0.15.0
      - fastapi==0.70.0
      - prometheus-client==0.11.0
      - PyYAML==6.0
      - hdbscan==0.8.27
      - umap-learn==0.5.2
      - top2vec==1.0.26
      - icecream==2.1.2
      - hnswlib==0.6.2